import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Torchlite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Torchlite!
        </h1>

        <div className={styles.grid}>
          <Link href="./dashboard">
            <h2>Dashboard</h2>
            <p>Visualize your worksets</p>
          </Link>

        </div>
      </main>

      <footer className={styles.footer}>
        HathiTrust Research Center
      </footer>
    </div>
  )
}
