import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Torchlite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Torchlite
        </h1>

        <div className={styles.grid}>
          <Link href="./worksets" className={styles.card}>
            <h2>Worksets</h2>
            <p>Choose a <a href="https://analytics.hathitrust.org/worksets">recommended workset</a>, or <a href="https://analytics.hathitrust.org/staticworksets">create your own.</a></p>
          </Link>

          <Link href="./widgets" className={styles.card}>
            <h2>Widgets</h2>
            <p>Browse and select tools for analyzing your workset.</p>
          </Link>

          <Link href="./dashboard" className={styles.card}>
            <h2>Dashboard</h2>
            <p>Shine a light on your workset: filter your data; use
            widgets to visualize.</p>
          </Link>

          <Link href="./notebooks" className={styles.card}>
            <h2>Notebooks</h2>
            <p>Share your results as Jupyter Notebooks.</p>
          </Link>

        </div>
      </main>

      <footer className={styles.footer}>
        HathiTrust Research Center
      </footer>
    </div>
  )
}
